project:
  type: website
  output-dir: docs



# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes


quarto:
  incremental: true


website:
  title: "HUAT-RRR"
  site-url: "https://.com"
  description: "RRR Resources"
  google-analytics: "G-P47K0XF3SM"
  page-footer:
    right: "Website is built with [Quarto](https://quarto.org/)."
    left: "Last Updated 01 Jan 2025"
    background: "#D9E3E4"
  navbar:
    search: true
    right:
      - text: "Workshop"
        file: ebp.qmd
      - text: "Journal Club"
        file: jclub.qmd
      - text: "R"
        file: R.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Articles"
        menu:
          - text: "JOSPT RTD"
            href: "articles/jospt_paper.pdf"
          - text: "Knee Isokinetic"
            href: "articles/knee_paper.pdf"      
          - text: "PTJ Step Test"
            href: "articles/ptj_steptest.pdf"      
 

 


format:
  html:
    toc: true
    toc-location: "right"
    code-link: true
    grid:
      margin-width: 350px
      body-width: 1000px
    anchor-sections: true
    # fig-cap-location: margin
    mainfont: "Lato"
    monofont: "Fira Mono"
    footnotes-hover: true
    fontsize: 1.1em
    theme: mock.scss
    css: styles.css
    reference-location: margin
    
    
    